"""Central configuration for the support triage pipeline."""

MODEL = "anthropic/claude-sonnet-4-5"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
TEMPERATURE = 0
SEED = 42
MAX_TOKENS = 1000

CHUNK_SIZE = 400
CHUNK_OVERLAP = 50
RETRIEVAL_TOP_K = 5
RETRIEVAL_CANDIDATE_K = 20
SEMANTIC_INJECTION_THRESHOLD = 0.72
MAX_CONTEXT_TOKENS = 5500
MAX_RETRIEVAL_TOKENS = 3500
MAX_CONVERSATION_TOKENS = 1500
PRODUCT_BOOST_FACTOR = 1.3

SAFE_ESCALATION_CONFIDENCE = 0.92
CONTRADICTION_MAX_CONFIDENCE = 0.60
MAX_LLM_RETRIES = 2
RETRY_BACKOFF_SECONDS = 2
